[package]
name = "gossip"
version = "0.1.0"
edition = "2024"

[dependencies]
human_ids = "0.1.1"

nanoid = "0.4.0"
tempdir = "0.3.7"
tokio = { version = "1.45.1", features = ["full"] }
tsnet = { git = "https://github.com/chrishayen/libtailscale", branch = "rust" }
